### ISSUE TITLE
Error return bug ?

### ISSUE THREAD

**Issue by krasi-georgiev** [funny/jsonrpc#1]
Hi

I am trying to use your library , but have some weird problem with it at line 36 of my code

https://github.com/vipconsult/portaBackend/blob/master/vhost.go#L36

line 38 returns error , but the php client receives NILL.

if I swap line 38 and 36 the php client receives the error

the client code is exactly the same as in your example

**Comment by bg5sbk** [comment]
Let me have a look :)

**Comment by bg5sbk** [comment]
Hi @vipconsult 

I add a unit test for RPC error return. But I can't reproduce your issue.

https://github.com/funny/jsonrpc/commit/0f0b3d055e3c9337fe50b687e2c27f7131b61a04

Are you sure `vh.Reload(args,reply)` returns an error?

**Comment by krasi-georgiev** [comment]
vh.Reload(args,reply) – is not important here because i have return errors.New("sadasd") right after it just for the troubleshooting.

i will look into the test you have created, maybe it will give me some clue

Kind Regards Chris

**Comment by krasi-georgiev** [comment]
I found the problem.

vh.Reload reloads the config files for the server where the php clients makes the request so this brakes the pipe and the php client looses the connection. 

I am trying to find out how to make the php client keep the connection open.

I remember I had this done via curl to another backend server and it didn’t have this problem so I might try with curl
